---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer4
server:
  port: 8004
eureka:
  instance:
    hostname: peer4
  client:
    serviceUrl:
      defaultZone: http://peer5:8005/eureka/,http://peer6:8006/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer5
server:
  port: 8005
eureka:
  instance:
    hostname: peer5
  client:
    serviceUrl:
      defaultZone: http://peer4:8004/eureka/,http://peer6:8006/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer6
server:
  port: 8006
eureka:
  instance:
    hostname: peer6
  client:
    serviceUrl:
      defaultZone: http://peer4:8004/eureka/,http://peer5:8005/eureka/